### ISSUE TITLE
bug: invalid theme

### ISSUE THREAD

**Issue by H4ppy-04** [coderefinery/documentation-example#3]
```
 ~/D/P/documentation (main) $ sphinx-build doc _build
Running Sphinx v6.1.3
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
making output directory... done

Theme error:
no theme named 'sphinx_rtd_theme' found (missing theme.conf?)
```

**Comment by bast** [comment]
Thanks for reporting. This example indeed requires `sphinx_rtd_theme` which is part of the CodeRefinery conda environment: https://coderefinery.github.io/installation/

@johanhellsvik @blindij can you please add a note to the README about requirements?

**Comment by H4ppy-04** [comment]
@bast Is this ok to close?

**Comment by bast** [comment]
I will send a patch in a minute.

**Comment by bast** [comment]
Fixed in https://github.com/coderefinery/documentation/commit/2006032b8bef8c584560d76995e9b70f94f1ae95
